[package]
name = "hpbf"
version = "0.1.0"
edition = "2021"

[features]
default = []
llvm = ["dep:inkwell"]

[dependencies]
inkwell = { version = "0.3.0", features = ["llvm17-0-prefer-dynamic"], optional = true }
